#!/usr/bin/env python2.7
# script by Alex Eames http://RasPi.tv/
# http://raspi.tv/2013/how-to-use-interrupts-with-python-on-the-raspberry-pi-and-rpi-gpio
import RPi.GPIO as GPIO
import os
GPIO.setmode(GPIO.BOARD)

# GPIO 23 set up as input. It is pulled up to stop false signals
GPIO.setup(12, GPIO.IN, pull_up_down=GPIO.PUD_UP)
GPIO.setup(16, GPIO.IN, pull_up_down=GPIO.PUD_UP)
GPIO.setup(18, GPIO.IN, pull_up_down=GPIO.PUD_UP)

try:
    GPIO.wait_for_edge(12, GPIO.FALLING)
    print "\nFalling edge detected. Now your program can continue with"
    os.system("sudo poweroff")
except KeyboardInterrupt:
    GPIO.cleanup()
try:
    GPIO.wait_for_edge(16, GPIO.FALLING)
    print "\nFalling edge detected. Now your program can continue with"
    os.system("startx &")
except KeyboardInterrupt:
    GPIO.cleanup()
try:
    GPIO.wait_for_edge(18, GPIO.FALLING)
    print "\nFalling edge detected. Now your program can continue with"
    os.system("ifconfig")
except KeyboardInterrupt:
    GPIO.cleanup()       # clean up GPIO on CTRL+C exit
GPIO.cleanup()           # clean up GPIO on normal exit
